name: Build and Deploy to Aruba Kubernetes

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build & push backend
      - name: Build & Push Backend
        run: |
          docker build -t $REGISTRY/$DOCKER_USER/backend:latest ./backend
          docker push $REGISTRY/$DOCKER_USER/backend:latest

      # Build & push frontend
      - name: Build & Push Frontend
        run: |
          docker build -t $REGISTRY/$DOCKER_USER/frontend:latest ./frontend
          docker push $REGISTRY/$DOCKER_USER/frontend:latest

      # Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/db-deployment.yaml
          kubectl apply -f k8s/db-service.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/ingress.yaml
